CREATE TABLE IF NOT EXISTS b_legacy_loyalty_program (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TYPE VARCHAR(50) NOT NULL,
    ACTIVE CHAR(1) DEFAULT 'Y',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);