CREATE TABLE IF NOT EXISTS b_legacy_loyalty_program (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TYPE VARCHAR(50) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    ACTIVE CHAR(1) DEFAULT 'N'
);

DELETE FROM b_legacy_loyalty_program;
INSERT INTO b_legacy_loyalty_program (TYPE, NAME, ACTIVE) VALUES
('bonus', 'Начисление/списание бонусов на заказ', 'N'),
('level', 'Разбиение пользователей на уровни', 'N'),
('event', 'Вознаграждения за события', 'N');

CREATE TABLE IF NOT EXISTS b_legacy_loyalty_bonus_rule (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    SORT INT DEFAULT 100,
    ACTIVE CHAR(1) DEFAULT 'Y',
    TYPE VARCHAR(20),
    AMOUNT INT,
    AMOUNT_TYPE VARCHAR(20),
    CONDITIONS TEXT
);

CREATE TABLE IF NOT EXISTS b_legacy_loyalty_bonus_history (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT,
    TYPE VARCHAR(50),
    AMOUNT INT,
    ORDER_ID INT NULL,
    SOURCE VARCHAR(50),
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS b_legacy_loyalty_bonus_user (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT,
    AMOUNT INT,
    ACTIVATE_AT DATE NULL,
    EXPIRE_AT DATE NULL
);

CREATE TABLE IF NOT EXISTS b_legacy_loyalty_level_rule (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    SORT INT DEFAULT 100,
    ACTIVE CHAR(1) DEFAULT 'Y',
    NAME VARCHAR(255),
    PERIOD INT NULL,
    CONDITIONS TEXT,
    PRIVILEGES TEXT
);

CREATE TABLE IF NOT EXISTS b_legacy_loyalty_level_history (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT,
    OLD_LEVEL_ID INT NULL,
    NEW_LEVEL_ID INT,
    SOURCE VARCHAR(50),
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS b_legacy_loyalty_level_user (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT,
    LEVEL_ID INT,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS b_legacy_loyalty_event_rule (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    SORT INT DEFAULT 100,
    ACTIVE CHAR(1) DEFAULT 'Y',
    NAME VARCHAR(255),
    TYPE VARCHAR(50),
    VALUE VARCHAR(255),
    CONDITIONS TEXT,
    PRIVILEGES TEXT
);

CREATE TABLE IF NOT EXISTS b_legacy_loyalty_event_history (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT,
    RULE_ID INT,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);